# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meter_data.proto\x12\x04\x64\x61ta\"-\n\tMeterData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x12\n\nmeterusage\x18\x02 \x01(\x02\"!\n\x11\x43reateDataRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"3\n\rGetDataResult\x12\"\n\tmeterdata\x18\x01 \x01(\x0b\x32\x0f.data.MeterDatab\x06proto3')



_METERDATA = DESCRIPTOR.message_types_by_name['MeterData']
_CREATEDATAREQUEST = DESCRIPTOR.message_types_by_name['CreateDataRequest']
_GETDATARESULT = DESCRIPTOR.message_types_by_name['GetDataResult']
MeterData = _reflection.GeneratedProtocolMessageType('MeterData', (_message.Message,), {
  'DESCRIPTOR' : _METERDATA,
  '__module__' : 'meter_data_pb2'
  # @@protoc_insertion_point(class_scope:data.MeterData)
  })
_sym_db.RegisterMessage(MeterData)

CreateDataRequest = _reflection.GeneratedProtocolMessageType('CreateDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATAREQUEST,
  '__module__' : 'meter_data_pb2'
  # @@protoc_insertion_point(class_scope:data.CreateDataRequest)
  })
_sym_db.RegisterMessage(CreateDataRequest)

GetDataResult = _reflection.GeneratedProtocolMessageType('GetDataResult', (_message.Message,), {
  'DESCRIPTOR' : _GETDATARESULT,
  '__module__' : 'meter_data_pb2'
  # @@protoc_insertion_point(class_scope:data.GetDataResult)
  })
_sym_db.RegisterMessage(GetDataResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METERDATA._serialized_start=26
  _METERDATA._serialized_end=71
  _CREATEDATAREQUEST._serialized_start=73
  _CREATEDATAREQUEST._serialized_end=106
  _GETDATARESULT._serialized_start=108
  _GETDATARESULT._serialized_end=159
# @@protoc_insertion_point(module_scope)
