# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import meter_data_pb2 as meter__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x1a\x10meter_data.proto2B\n\x04\x44\x61ta\x12:\n\nCreateData\x12\x17.data.CreateDataRequest\x1a\x13.data.GetDataResultb\x06proto3')



_DATA = DESCRIPTOR.services_by_name['Data']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=40
  _DATA._serialized_end=106
# @@protoc_insertion_point(module_scope)
